### ISSUE TITLE
Build eror with -Werror=incompatible-pointer-types (i.e. gcc-14)

### ISSUE THREAD

**Issue by ametzler** [hannob/uudeview#24]
Hello,

gcc-14 bumps `-Wincompatible-pointer-types` from warning to error which makes uudeview FTBFS.
cu Andreas

**Comment by ametzler** [comment]
Hello Hanno,
the error shows both in 0.5.20 and GIT head in the tcl code.

I seem to be unable to get a successful --enable-tcl outside the Debian package and am too stupid to see the reason. Anyway the respective buildlog looks like this
[buildlog.uudeview_0.5.20+20230502-2_amd64.txt](https://github.com/user-attachments/files/16174520/buildlog.uudeview_0.5.20%2B20230502-2_amd64.txt)

**Comment by hannob** [comment]
Ok, should be fixed now with https://github.com/hannob/uudeview/commit/7b04dc19ba91109316b09c14b370c50b2d492913

We should also enable compilation with tcl+tk in CI so such issues get caught automatically, see #26

**Comment by ametzler** [comment]
> Ok, should be fixed now with [7b04dc1](https://github.com/hannob/uudeview/commit/7b04dc19ba91109316b09c14b370c50b2d492913)

It is, I just did a rebuild with gcc-14 to doublecheck.

Thank you!
